### ISSUE TITLE
Favicon shouldnt seem to change from the CouchDB logo

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb-fauxton#13]
Not sure if this is just me, the favicon supplied at the repo of the repo doesn't end up being used.

**Comment by nolanlawson** [comment]
This might just be your browser caching it. Try opening it up in a private tab.

**Comment by nickcolley** [comment]
Yeah I tried that, think it must be a build step thing?

**Comment by NickColley** [comment]
Closing old issues.
