### ISSUE TITLE
Merge with Fauxton master

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-fauxton#7]
So basically I tried to do

```
git merge 9aafbd80e3a4545c292ca4c3251648fc0c80928a
```

But I found that there were too many merge conflicts. @nickcolley, it seems that notably there are a lot of conflicts where you added branding colors to `fauxton.less`, but those styles were refactored out into new `less` files and so now we need to apply the changes over again. :(

**Comment by nickcolley** [comment]
I refactored those as all the colours were hardcoded in fauxton, I contributed it back upstream but I think potentially it's different.

Hopefully there's not much to redo with that in mind but happy to merge this for you.

**Comment by nickcolley** [comment]
Had a proper look and it looks okay, I should be able to merge it successfully.

The main repo is using 'master' whereas we're using import-master. Any idea why we're not using the master branch?

**Comment by nolanlawson** [comment]
I think `import-master` was because this was forked from a GitHub repo that was mirrored from somewhere else.

**Comment by nickcolley** [comment]
Can we make master the default branch?

**Comment by nolanlawson** [comment]
@nickcolley Sure, I think the whole `import-master` thing is an artifact of having forked a mirror of a non-Github repo.
