### ISSUE TITLE
Can't remove a database

### ISSUE THREAD

**Issue by marten-de-vries** [pouchdb/pouchdb-fauxton#8]
See also https://github.com/marten-de-vries/pouchdb-fauxton-chrome-extension/issues/4 , although you can reproduce it with just plain express-pouchdb/pouchdb-server too. Considering CouchDB's Fauxton isn't experiencing this problem, fixing #7 would probably fix this as well.

**Comment by nickcolley** [comment]
@marten-de-vries is this a problem still? :cactus:

**Comment by marten-de-vries** [comment]
No, this was fixed for express-pouchdb. (Not the browser plug-ins for yet to be debugged reasons).
